[tool.poetry]
name = "harambe"
version = "0.5.2"
description = "Data extraction SDK for Playwright 🐒🍌"
authors = ["awtkns <hello@awtkns.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
playwright = "^1.39.0"
playwright-stealth = { git = "https://github.com/AtuboDad/playwright_stealth.git" }
setuptools = "^69.0.2"
beautifulsoup4 = "^4.12.2"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.2.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.1"
pytest-mock = "^3.12.0"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
